### ISSUE TITLE
Can Date of Service be passed as a parameter

### ISSUE THREAD

**Issue by bopritchard** [GoodMeasuresLLC/trizetto-api#2]
Can Date of Service be passed as a parameter?
Thanks

**Comment by johnnaegle** [comment]
Yes, if you pass DateOfService as "YYYYMMDD" it appears to work.

```ruby
response = client.do_inquiry({
  'ProviderLastName': 'YOUR_COMPANY_NAME',
  'NPI':              'YOUR NPI HERE',
  'InsuredFirstName': 'Mickey',
  'InsuredLastName':  'Mouse',
  'InsuredDob':       '19281118',
  'GediPayerId':      'N4222',
  'DateOfService: '20190524'
})
```

[Trizetto's documentation](https://mytools.gatewayedi.com/Help/documents/Eligibility/Realtime%20Eligibility%20Webservice%20Companion%20Guide.pdf) doesn't mention this

**Comment by johnnaegle** [comment]
FWIW, I updated the readme with the fields I know about
